# Generated by Django 5.0.3 on 2024-03-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_note_badge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date',
            new_name='created_at',
        ),
    ]
