# Generated by Django 5.0.4 on 2024-04-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_date_note_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
