# Generated by Django 5.0.4 on 2024-04-19 13:29

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_note_note_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
    ]
