name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Navigate to webapp directory
        run: cd Webapp/webapp

      - name: Install dependencies
        working-directory: Webapp/webapp
        run: npm install

      - name: Build project
        working-directory: Webapp/webapp
        run: npm run build

      - name: Build Project 🏗️
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_URL }}
          VITE_PUBLIC_URL: ${{ secrets.VITE_API_URL }}
        run: npm run build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "sanjai-notes"
          entrypoint: "https://deno.land/std@0.217.0/http/file_server.ts"
          root: "Webapp/webapp/dist"